POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "test1", "password": "test1"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "test1", "password": "test1", "email": "test1@test.com"}

###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 1799e175e2ff4e2bf77d19bebdaf6eb875c00869

{}

###

GET http://127.0.0.1:8000/api/apps
Content-Type: application/json

{}

###

POST http://127.0.0.1:8000/api/create-app
Content-Type: multipart/form-data

{
    "name": "Test App 2",
    "link": "testapp2.com",
    "category": "entertaiment",
    "sub_category": "social media",
    "icon": "./facebook.png"
  }
